logo: /assets/img/logo.png
show_downloads: false
theme: jekyll-theme-minimal
title: Nasr Kasrin
roles: R&D / product development / software architecture
subjects: Metadata Managment | Data Architecture | mobile & social | web
