logo: /assets/img/logo.png
show_downloads: false
theme: jekyll-theme-minimal
title: NASR KASRIN
roles: Defy the Maker/Manager Split
email: nk.txpct@aleeas.com
linkedin: nkasrin
german: index_de
resume_url: https://raw.githubusercontent.com/n42r/n42r.github.io/main/assets/pdf/kasrin-resume.pdf
