logo: /assets/img/logo.png
show_downloads: false
theme: jekyll-theme-minimal
title: NASR KASRIN
roles: Solution Architect | Tech Leader
email: n42r.me@gmail.com
linkedin: nkasrin
github: https://github.com/n42r
german: index_de
resume_url: https://raw.githubusercontent.com/n42r/n42r.github.io/main/assets/pdf/kasrin_resume.pdf
