logo: /assets/img/logo.png
show_downloads: false
theme: jekyll-theme-minimal
title: Nasr Kasrin (Dr.)
headline: "Technical leader and builder &middot; Writing about software engineering in the age of AI"
roles:
email: nasr.kasrin@gmail.com
linkedin: nkasrin
blog: ./blog
github:
german:
resume_url: "./assets/pdf/resume_kasrin.pdf"